package com.uvrs.enums;

public enum PricingMethod {
    PER_HOUR,
    PER_MILE,
    PER_KILOMETER,
    CAPACITY_BASED,
    SUBSCRIPTION_MEMBERSHIP,
    FLAT_RATE,
    ZONE_BASED,
    PEAK_OFF_PEAK,
    DEMAND_BASED_DYNAMIC,
    SPECIALIZED_SERVICE_PACKAGES,
    ENVIRONMENTAL_GREEN,
    GOVERNMENT_REGULATORY;
}
